CREATE USER LOANS
  IDENTIFIED BY holamundo1
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA 20M on USERS;
  
  
ALTER USER "LOANS" QUOTA UNLIMITED ON USERS;
GRANT CONNECT,RESOURCE, DBA TO "LOANS"  ;
GRANT CREATE ANY SEQUENCE   TO LOANS;
CREATE TABLE LOANS.TEMP (NUMEROS NUMBER);
CREATE SEQUENCE LOANS.SEQ_NUMBER INCREMENT BY 1 START WITH 1 MAXVALUE 9999999 MINVALUE 1 NOCACHE;

