DROP TABLE LOANS.LOAN_TYPE;
DROP TABLE LOANS.LOAN;
DROP TABLE LOANS.LOAN2;
DROP TABLE LOANS.CUSTOMER;
DROP TABLE LOANS.PAYMENT2;
DROP TABLE LOANS.PAYMENT;
DROP TABLE LOANS.TEMP;
DROP SEQUENCE LOANS.SEQ_NUMBER