OPTIONS (
	SKIP=1,
	ERRORS=0,
	DIRECT=FALSE
	)
LOAD DATA
INFILE "..\files\LOAN.csv" "STR x'0A'"
BADFILE "C_0LOA.bad"
DISCARDFILE "C_0LOA.dsc"
DISCARDMAX 1
INTO TABLE LOANS.LOAN2
FIELDS TERMINATED BY X'2C'
TRAILING NULLCOLS
(
	id	DECIMAL EXTERNAL,
	customer_id	DECIMAL EXTERNAL,
	type_id	DECIMAL EXTERNAL,
	amount	DECIMAL EXTERNAL,
	created_date	DATE "YYYY-MM-DD",
	is_complete	DECIMAL EXTERNAL
)
  