OPTIONS (
	SKIP=1,
	ERRORS=0,
	DIRECT=FALSE
	)
LOAD DATA
INFILE "..\files\PAYMENT.csv" "STR x'0A'"
BADFILE "C_0PAY.bad"
DISCARDFILE "C_0PAY.dsc"
DISCARDMAX 1
INTO TABLE LOANS.PAYMENT 
FIELDS TERMINATED BY X'2C'
TRAILING NULLCOLS
(
	id	DECIMAL EXTERNAL,
	loan_id	DECIMAL EXTERNAL,
	payment_number	DECIMAL EXTERNAL,
	amount	FLOAT EXTERNAL
)
  