OPTIONS (
	SKIP=1,
	ERRORS=0,
	DIRECT=FALSE
	)
LOAD DATA
INFILE "..\files\LOAN_TYPE.csv" "STR x'0A'"
BADFILE "/C_0LOAN.bad"
DISCARDFILE "/C_0LOAN.dsc"
DISCARDMAX 1
INTO TABLE LOANS.LOAN_TYPE
FIELDS TERMINATED BY X'2C'
TRAILING NULLCOLS
(
	id	DECIMAL EXTERNAL,
	type	,
	created_date	 DATE "dd/MM/YY"
)
  